import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          {/* Sidebar fixed on the left */}
          <Sidebar />

          <div className="flex-1 ml-[80px]">
            {" "}
            {/* push main content to the right */}
            {/* Fixed header */}
            <Header />
            {/* Scrollable content */}
            <main className="mt-[80px] p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
